server:
  port: 8083


spring:
  application:
    name: demo-order
  config:
    import: "optional:configserver:http://localhost:8888"


  #cloud:
    #config:
      #uri: ${CONFIG_SERVER_URL}
      #import:
       # configserver: http://localhost:8888
    #profiles:
      #active: dev
#  jpa:
#    hibernate:
#      ddl-auto: none
#    show-sql: true

#  datasource:
#    url: jdbc:mysql://localhost:3306/dbproductos
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}


logging:
  level:
    org:
      springframework:
        security: TRACE